name: Scala CI

on:
  push:
    branches: [  ci_testing  ]
  pull_request:
    branches: [  ci_testing  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Compilation  
      run: sbt compile
    - name: Run Tests
      run: sbt test
